// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace srikanthkonnagula.Models;

public partial class AppliedTrainings
{
    public int AppliedTrainingId { get; set; }

    public int? EmployeeId { get; set; }

    public int? TrainingId { get; set; }

    public string CourseName { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual TrainingData Training { get; set; }
}