// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace srikanthkonnagula.Models;

public partial class Attendence
{
    public int AttendenceId { get; set; }

    public int? EmployeeId { get; set; }

    public int? TrainingId { get; set; }

    public DateTime? Date { get; set; }

    public bool Attendence1 { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual TrainingData Training { get; set; }
}