// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace srikanthkonnagula.Models;

public partial class Employee
{
    public int EmployeeId { get; set; }

    public int? UserId { get; set; }

    public int? ManagerId { get; set; }

    public string EmployeeName { get; set; }

    public string Email { get; set; }

    public string Mobile { get; set; }

    public virtual ICollection<AppliedTrainings> AppliedTrainings { get; set; } = new List<AppliedTrainings>();

    public virtual ICollection<Attendence> Attendence { get; set; } = new List<Attendence>();

    public virtual ManagerData Manager { get; set; }

    public virtual ICollection<TraineeRegistration> TraineeRegistration { get; set; } = new List<TraineeRegistration>();

    public virtual UserDetails User { get; set; }
}