// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace srikanthkonnagula.Models;

public partial class Feedback
{
    public int FeedbackId { get; set; }

    public int? TrainingId { get; set; }

    public int? EmployeeId { get; set; }

    public string FbMessage { get; set; }

    public DateTime? FeedbackDate { get; set; }
}