// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace srikanthkonnagula.Models;

public partial class TrainingData
{
    public int TrainingId { get; set; }

    public string CourseName { get; set; }

    public string Description { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? Enddate { get; set; }

    public virtual ICollection<AppliedTrainings> AppliedTrainings { get; set; } = new List<AppliedTrainings>();

    public virtual ICollection<Attendence> Attendence { get; set; } = new List<Attendence>();

    public virtual ICollection<TraineeRegistration> TraineeRegistration { get; set; } = new List<TraineeRegistration>();
}