// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace srikanthkonnagula.Models;

public partial class TraineeRegistration
{
    public int RegId { get; set; }

    public int? TrainingId { get; set; }

    public int? EmployeeId { get; set; }

    public string Status { get; set; }

    public string Reason { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual TrainingData Training { get; set; }
}