// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace srikanthkonnagula.Models;

public partial class UserDetails
{
    public int UserId { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public string UserType { get; set; }

    public virtual ICollection<Employee> Employee { get; set; } = new List<Employee>();

    public virtual ICollection<ManagerData> ManagerData { get; set; } = new List<ManagerData>();
}